version: '3.7'
services:
  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: insitulabs
      MONGO_INITDB_ROOT_PASSWORD: insitulabs
      MONGO_INITDB_DATABASE: app
    volumes:
      - ./docker-config/mongo:/docker-entrypoint-initdb.d
